---
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages on servers
  apt:
    upgrade: dist

- name: Install required packages
  apt:
    name:
      - mysql-server
      - nginx
      - php7.4
      - php7.4-mbstring
      - php7.4-fpm
      - php7.4-cli
      - php7.4-mysql
      - php7.4-curl
      - php7.4-json
      - python2
      - make
      - g++
      - redis-server
      - acl
      - net-tools
    state: latest

- name: Copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/

- name: Copy nginx default file
  copy:
    src: default
    dest: /etc/nginx/sites-available

- name: Copy PHP configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/php/7.4/fpm/
  with_items:
    - php.ini
    - www.conf

- name: Copy MySQL configuration file
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/

- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Install OpenSSL package
  apt:
    name: openssl
    state: latest

- name: Install Node.js using NVM (ubuntu user)
  become: true
  become_user: ubuntu
  shell: |
    export NVM_DIR="/home/ubuntu/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install v18.14.0
    nvm use v18.14.0

- name: Install PM2 globally (ubuntu user)
  become: true
  become_user: ubuntu
  shell: |
    export NVM_DIR="/home/ubuntu/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install pm2 -g

- name: Install PM2 logrotate module (ubuntu user)
  become: true
  become_user: ubuntu
  shell: |
    export NVM_DIR="/home/ubuntu/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    pm2 install pm2-logrotate

- name: Configure PM2 log rotation settings (ubuntu user)
  become: true
  become_user: ubuntu
  shell: |
    export NVM_DIR="/home/ubuntu/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    pm2 set pm2-logrotate:retain 3
    pm2 set pm2-logrotate:compress true
    pm2 set pm2-logrotate:max_size 1M

- name: Restart nginx Service
  service:
    name: nginx
    state: restarted

- name: Restart redis-server Service
  service:
    name: redis-server
    state: restarted